
[window]
opacity = 0.9
padding.x = 10
padding.y = 10
decorations = "Buttonless"
decorations_theme_variant = "Dark"

[font]
normal.family = "0xProto"
bold.family = "0xProto"
italic.family = "0xProto"
bold_italic.family = "0xProto"
size = 13.0

